/**
 * Ghost Touch Survey — Internationalization (EN/ZH)
 */
const I18N = (() => {
  let currentLang = 'en';

  const translations = {
    en: {
      // Header
      title: 'Ghost Touch: Haptic Profile Evaluation',
      subtitle: 'Evaluating how well haptic profiles match descriptions of ghost-touch sensations',

      // Progress
      complete: 'complete',

      // Consent
      consent_title: 'Informed Consent',
      consent_purpose_title: 'Purpose',
      consent_purpose: 'This study investigates whether computer-generated haptic (touch) profiles meaningfully correspond to descriptions of ghost-touch sensations. Your task is to match text descriptions to visual representations of haptic profiles, and to rank different haptic profiles by how well they match descriptions.',
      consent_whatyoudo_title: 'What You Will Do',
      consent_part1: '<strong>Part 1 (~5 min):</strong> Read 10 short ghost-touch descriptions and select the best-matching haptic profile from 3 options.',
      consent_part2: '<strong>Part 2 (~5 min):</strong> Read 10 descriptions and rank 3 haptic profiles by how well each matches.',
      consent_part3: '<strong>Brief demographics and debrief (~2 min).</strong>',
      consent_haptic_title: 'Haptic Profiles',
      consent_haptic: 'Each haptic profile is shown as a visual card with an animated waveform and parameter bars. You do <strong>not</strong> need any special hardware or experience with haptics. Use your intuition to judge which profile "feels" like the description based on the visual cues (vibration pattern, strength, temperature, roughness, timing).',
      consent_risks_title: 'Risks & Benefits',
      consent_risks: 'No known risks beyond normal computer use. The study contributes to research on haptic design for virtual reality. You will be compensated at the Prolific standard rate.',
      consent_data_title: 'Data & Privacy',
      consent_data: 'Your responses are anonymous. We collect no personally identifiable information. Anonymized data may be published in academic papers.',
      consent_rights_title: 'Your Rights',
      consent_rights: 'Participation is voluntary. You may withdraw at any time by closing the browser. If you withdraw, your data will not be used.',
      consent_agree: 'I have read and understood the above information. I am 18 years or older. I voluntarily agree to participate in this study.',
      btn_continue: 'Continue',
      consent_check_alert: 'Please check the consent box to continue.',

      // Demographics
      demo_title: 'About You',
      demo_age: 'Age range',
      demo_age_select: 'Select...',
      demo_gender: 'Gender',
      demo_gender_select: 'Select...',
      demo_gender_female: 'Female',
      demo_gender_male: 'Male',
      demo_gender_nb: 'Non-binary / Third gender',
      demo_gender_pnts: 'Prefer not to say',
      demo_vr: 'VR / haptic device experience',
      demo_vr_never: 'Never used',
      demo_vr_occasionally: 'Occasionally',
      demo_vr_regularly: 'Regularly',
      demo_ghost: 'How familiar are you with ghost/supernatural media? (movies, games, books, shows)',
      demo_ghost_not: 'Not at all',
      demo_ghost_somewhat: 'Somewhat',
      demo_ghost_very: 'Very familiar',
      demo_alert: 'Please answer all demographic questions.',

      // Part 1
      part1_title: 'Part 1: Matching Task',
      part1_desc: 'You will read <strong>10 short descriptions</strong> of ghost-touch sensations. For each description, you will see <strong>3 haptic profile cards</strong>. Each card visualizes a different set of haptic parameters:',
      part1_param_wave: '<strong>Animated waveform:</strong> shows the vibration pattern (shape, speed, noise level)',
      part1_param_amp: '<strong>Amplitude:</strong> how strong the vibration is',
      part1_param_thermal: '<strong>Thermal:</strong> temperature shift from cold (blue, left) to warm (red, right)',
      part1_param_rough: '<strong>Roughness:</strong> how smooth vs. rough/noisy the texture is',
      part1_param_onset: '<strong>Onset:</strong> how quickly the sensation starts',
      part1_param_dur: '<strong>Duration:</strong> how long the sensation lasts',
      part1_task: '<strong>Your task:</strong> Select the profile card that best matches the described sensation. Trust your intuition!',
      btn_start_part1: 'Start Part 1',
      part1_label: 'Part 1: Matching',
      part1_trial: 'Trial',
      part1_of: 'of',
      part1_excerpt_label: 'Ghost-Touch Description',
      part1_instruction: 'Which haptic profile best matches the sensation described above? Click to select.',
      btn_back: 'Back',
      btn_next: 'Next',

      // Part 2
      part2_title: 'Part 2: Preference Ranking',
      part2_desc: 'You will read <strong>10 descriptions</strong> (one for each type of ghost-touch). For each, you will see <strong>3 haptic profiles</strong> generated by different methods.',
      part2_task: '<strong>Your task:</strong> Rank the 3 profiles from <strong>1st (best match)</strong> to <strong>3rd (worst match)</strong>.',
      part2_how: 'To assign a rank: click a profile card to select it, then click a rank button (1st, 2nd, or 3rd).',
      btn_start_part2: 'Start Part 2',
      part2_label: 'Part 2: Preference',
      part2_instruction: 'Rank these haptic profiles from best match (1st) to worst match (3rd) for the description above.<br>Click a profile, then click a rank button to assign it.',
      rank_assign: 'Assign rank:',
      rank_1: '1st',
      rank_2: '2nd',
      rank_3: '3rd',
      rank_alert: 'Click a profile card first, then assign a rank.',

      // Params
      param_amplitude: 'Amplitude',
      param_thermal: 'Thermal',
      param_roughness: 'Roughness',
      param_onset: 'Onset',
      param_duration: 'Duration',

      // Debrief
      debrief_title: 'Final Questions',
      debrief_strategy: 'How did you decide which profile matched the text? What features did you focus on?',
      debrief_strategy_ph: 'e.g., I looked at the temperature for cold descriptions, or I focused on the waveform pattern...',
      debrief_comments: 'Any other comments or feedback about the survey? (optional)',
      debrief_comments_ph: 'Optional feedback...',
      btn_submit: 'Submit',

      // Completion
      thankyou: 'Thank You!',
      responses_recorded: 'Your responses have been recorded.',
      responses_failed: 'Note: We could not save your data to our server, but your completion is still valid.',
      responses_local: 'Data saved locally (no webhook configured).',
      accuracy_label: 'Your accuracy on Part 1 (matching):',
      redirecting: 'Redirecting you back to Prolific...',
      redirect_manual: 'If you are not redirected automatically,',
      redirect_click: 'click here',
      completion_code: 'Completion code:',
      btn_download: 'Download Response Data (JSON)',
      completion_note: 'You may now close this page. Thank you for your contribution to haptic research!',
      submitting: 'Submitting your responses...',
      submitting_wait: 'Please wait while we save your data.',

      // None match + custom
      none_match: 'None of these match well',
      none_match_reason_ph: 'Briefly describe what you expected (optional)',
      custom_title: 'Design your ideal haptic profile:',
      custom_amp: 'Vibration Strength',
      custom_freq: 'Vibration Speed',
      custom_thermal: 'Temperature',
      custom_thermal_cold: 'Cold',
      custom_thermal_hot: 'Hot',
      custom_rough: 'Roughness',
      custom_rough_smooth: 'Smooth',
      custom_rough_rough: 'Rough',
      custom_onset: 'Start Speed',
      custom_onset_slow: 'Slow',
      custom_onset_fast: 'Fast',
      custom_dur: 'Duration',
      custom_dur_short: 'Short',
      custom_dur_long: 'Long',

      // Language
      lang_switch: '中文',
    },

    zh: {
      title: 'Ghost Touch: 触觉配置文件评估',
      subtitle: '评估触觉配置文件与幽灵触感描述的匹配程度',

      complete: '完成',

      consent_title: '知情同意',
      consent_purpose_title: '研究目的',
      consent_purpose: '本研究旨在探究计算机生成的触觉配置文件是否能有效对应幽灵触感的文字描述。您的任务是将文字描述与触觉配置文件的可视化表示进行匹配，并对不同的触觉配置文件按匹配程度进行排序。',
      consent_whatyoudo_title: '您将做什么',
      consent_part1: '<strong>第一部分（约5分钟）：</strong>阅读10段幽灵触感的描述，从3个选项中选择最匹配的触觉配置文件。',
      consent_part2: '<strong>第二部分（约5分钟）：</strong>阅读10段描述，对3个触觉配置文件按匹配程度排序。',
      consent_part3: '<strong>简短的基本信息和反馈（约2分钟）。</strong>',
      consent_haptic_title: '触觉配置文件',
      consent_haptic: '每个触觉配置文件以可视化卡片的形式呈现，包含动态波形和参数条。您<strong>不需要</strong>任何特殊硬件或触觉相关经验。请凭直觉根据视觉线索（振动模式、强度、温度、粗糙度、时间）判断哪个配置文件"感觉"更像描述中的触感。',
      consent_risks_title: '风险与收益',
      consent_risks: '除正常使用电脑外，无已知风险。本研究有助于虚拟现实触觉设计的研究。您将按照 Prolific 标准费率获得报酬。',
      consent_data_title: '数据与隐私',
      consent_data: '您的回答是匿名的。我们不收集任何可识别个人身份的信息。匿名数据可能会发表在学术论文中。',
      consent_rights_title: '您的权利',
      consent_rights: '参与是自愿的。您可以随时关闭浏览器退出研究。如果您退出，您的数据将不会被使用。',
      consent_agree: '我已阅读并理解以上信息。我已年满18周岁。我自愿同意参与本研究。',
      btn_continue: '继续',
      consent_check_alert: '请勾选同意框以继续。',

      demo_title: '关于您',
      demo_age: '年龄范围',
      demo_age_select: '请选择...',
      demo_gender: '性别',
      demo_gender_select: '请选择...',
      demo_gender_female: '女',
      demo_gender_male: '男',
      demo_gender_nb: '非二元/第三性别',
      demo_gender_pnts: '不愿透露',
      demo_vr: 'VR / 触觉设备使用经验',
      demo_vr_never: '从未使用',
      demo_vr_occasionally: '偶尔使用',
      demo_vr_regularly: '经常使用',
      demo_ghost: '您对鬼怪/超自然媒体的熟悉程度？（电影、游戏、书籍、剧集）',
      demo_ghost_not: '完全不熟悉',
      demo_ghost_somewhat: '有些了解',
      demo_ghost_very: '非常熟悉',
      demo_alert: '请回答所有问题。',

      part1_title: '第一部分：匹配任务',
      part1_desc: '您将阅读 <strong>10段</strong> 幽灵触感描述。每段描述下方有 <strong>3张触觉配置卡片</strong>，每张卡片展示一组不同的触觉参数：',
      part1_param_wave: '<strong>动态波形：</strong>显示振动模式（形状、速度、噪声水平）',
      part1_param_amp: '<strong>振幅：</strong>振动的强弱',
      part1_param_thermal: '<strong>温度：</strong>温度变化，从冷（蓝色，左侧）到热（红色，右侧）',
      part1_param_rough: '<strong>粗糙度：</strong>纹理的光滑与粗糙程度',
      part1_param_onset: '<strong>起始时间：</strong>触感开始的快慢',
      part1_param_dur: '<strong>持续时间：</strong>触感持续的长短',
      part1_task: '<strong>您的任务：</strong>选择最匹配描述中触感的配置卡片。请相信您的直觉！',
      btn_start_part1: '开始第一部分',
      part1_label: '第一部分：匹配',
      part1_trial: '第',
      part1_of: '题，共',
      part1_excerpt_label: '幽灵触感描述',
      part1_instruction: '哪个触觉配置文件最匹配以上描述的触感？点击选择。',
      btn_back: '上一题',
      btn_next: '下一题',

      part2_title: '第二部分：偏好排序',
      part2_desc: '您将阅读 <strong>10段描述</strong>（每种幽灵触感类型各一段）。每段描述下方有 <strong>3个触觉配置文件</strong>，由不同方法生成。',
      part2_task: '<strong>您的任务：</strong>将3个配置文件从 <strong>最匹配（第1名）</strong> 到 <strong>最不匹配（第3名）</strong> 进行排序。',
      part2_how: '操作方法：先点击一个配置卡片选中它，然后点击排名按钮（第1、第2或第3）。',
      btn_start_part2: '开始第二部分',
      part2_label: '第二部分：偏好排序',
      part2_instruction: '请将这些触觉配置文件按与描述的匹配程度排序（第1名=最匹配，第3名=最不匹配）。<br>先点击配置卡片，再点击排名按钮。',
      rank_assign: '分配排名：',
      rank_1: '第1',
      rank_2: '第2',
      rank_3: '第3',
      rank_alert: '请先点击一个配置卡片，再分配排名。',

      param_amplitude: '振幅',
      param_thermal: '温度',
      param_roughness: '粗糙度',
      param_onset: '起始',
      param_duration: '时长',

      debrief_title: '最后几个问题',
      debrief_strategy: '您是如何判断哪个配置文件与文字描述匹配的？您关注了哪些特征？',
      debrief_strategy_ph: '例如：对于冷的描述我会看温度参数，或者我主要关注波形模式...',
      debrief_comments: '您对本问卷有其他意见或反馈吗？（可选）',
      debrief_comments_ph: '可选反馈...',
      btn_submit: '提交',

      thankyou: '感谢参与！',
      responses_recorded: '您的回答已成功记录。',
      responses_failed: '提示：我们无法将数据保存到服务器，但您的完成状态仍然有效。',
      responses_local: '数据已保存到本地（未配置数据收集服务）。',
      accuracy_label: '您在第一部分（匹配）的正确率：',
      redirecting: '正在将您重定向回 Prolific...',
      redirect_manual: '如果没有自动跳转，请',
      redirect_click: '点击这里',
      completion_code: '完成码：',
      btn_download: '下载回答数据 (JSON)',
      completion_note: '您现在可以关闭此页面。感谢您对触觉研究的贡献！',
      submitting: '正在提交您的回答...',
      submitting_wait: '请稍候，正在保存数据。',

      none_match: '以上选项均不太匹配',
      none_match_reason_ph: '简要描述您期望的触感（可选）',
      custom_title: '设计您理想中的触觉配置：',
      custom_amp: '振动强度',
      custom_freq: '振动速度',
      custom_thermal: '温度',
      custom_thermal_cold: '冷',
      custom_thermal_hot: '热',
      custom_rough: '粗糙度',
      custom_rough_smooth: '光滑',
      custom_rough_rough: '粗糙',
      custom_onset: '起始速度',
      custom_onset_slow: '慢',
      custom_onset_fast: '快',
      custom_dur: '持续时间',
      custom_dur_short: '短',
      custom_dur_long: '长',

      lang_switch: 'English',
    },
  };

  function t(key) {
    return (translations[currentLang] && translations[currentLang][key]) || translations.en[key] || key;
  }

  function setLang(lang) {
    currentLang = lang;
    try { localStorage.setItem('ghost_touch_lang', lang); } catch(e) {}
  }

  function getLang() { return currentLang; }

  // Auto-detect from browser or saved preference
  function detectLang() {
    try {
      const saved = localStorage.getItem('ghost_touch_lang');
      if (saved && translations[saved]) { currentLang = saved; return; }
    } catch(e) {}
    const nav = navigator.language || '';
    if (nav.startsWith('zh')) currentLang = 'zh';
  }

  detectLang();

  return { t, setLang, getLang, translations };
})();
